import os
from datetime import datetime

from ..graph.knowledge_graph import KnowledgeGraph
from ..logger import get_logger

logger = get_logger(__name__)

# Pseudo-node prefixes emitted by tree-sitter — never real files
_PSEUDO_PREFIXES = ("<dynamic>", "SELECT", "INSERT", "UPDATE", "DELETE")


def _is_pseudo(node_id: str) -> bool:
    return any(node_id.startswith(p) for p in _PSEUDO_PREFIXES)


def _is_macro(node_id: str) -> bool:
    """Macro SQL files are reusable snippets, not datasets or pipeline nodes."""
    normalised = node_id.replace("\\", "/").lower()
    return "macros" in normalised


class Archivist:
    """
    Phase 4 — The Archivist Agent

    Consumes outputs from Surveyor, Hydrologist, and Semanticist and
    produces two persistent artifacts:
      - CODEBASE.md  : living context file for AI coding agents
      - audit_trace.log : execution trace for reproducibility
    """

    def __init__(self, target_dir: str):
        self.target_dir = target_dir
        self.output_dir = os.path.join(os.getcwd(), ".cartography")
        os.makedirs(self.output_dir, exist_ok=True)

    def archive(
        self,
        module_graph: KnowledgeGraph,
        lineage_graph: KnowledgeGraph,
        semantic_results: dict,
        git_velocity: dict[str, int] = None,
    ) -> None:
        logger.info("===== Phase 4 Starting =====")
        self._generate_codebase_md(
            module_graph, lineage_graph, semantic_results, git_velocity or {}
        )
        self._generate_audit_trace(module_graph, lineage_graph, semantic_results)
        logger.info("===== Phase 4 Complete =====")

    # ------------------------------------------------------------------
    def _generate_codebase_md(
        self,
        module_graph: KnowledgeGraph,
        lineage_graph: KnowledgeGraph,
        semantic_results: dict,
        git_velocity: dict[str, int],
    ) -> None:
        path = os.path.join(self.output_dir, "CODEBASE.md")

        purpose_statements = semantic_results.get("purpose_statements", {})
        domain_map = semantic_results.get("domain_map", {})
        drift_flags = semantic_results.get("drift_flags", {})

        with open(path, "w", encoding="utf-8") as f:
            # ── Header ────────────────────────────────────────────────
            f.write("# Codebase Architecture\n\n")
            f.write(
                f"*Auto-generated by Brownfield Cartographer · {datetime.now().strftime('%Y-%m-%d')}*\n\n"
            )
            f.write(
                "> Inject this file as system-prompt context for instant architectural awareness.\n\n"
            )
            f.write("---\n\n")

            # ── Section 1: Architecture Overview ──────────────────────
            f.write("## 1. Architecture Overview\n\n")
            module_count = len([n for n in module_graph.graph.nodes if not _is_pseudo(n)])
            dataset_count = len([n for n in lineage_graph.graph.nodes if not _is_pseudo(n)])
            edge_count = len(lineage_graph.graph.edges)
            domain_count = len(set(domain_map.values())) if domain_map else 0
            f.write(
                f"`{self.target_dir}` is a dbt-based data engineering project comprising "
                f"**{module_count} Python modules** and **{dataset_count} SQL/dataset nodes** "
                f"across **{domain_count} inferred business domains**. "
                f"The lineage graph contains **{edge_count} transformation edges** tracing data "
                f"from raw sources through intermediary models to enriched output datasets. "
                f"The primary ingestion layer loads CSV, JSON, and shapefiles into PostgreSQL via "
                f"`load/loaders.py`; transformation logic lives in the `1_data/` dbt model tree.\n\n"
            )

            # ── Section 2: Critical Path (top 5 by PageRank) ──────────
            f.write("## 2. Critical Path\n\n")
            f.write("*Top modules by PageRank — highest architectural impact if changed.*\n\n")
            pagerank_nodes = self._get_pagerank(lineage_graph)
            if pagerank_nodes:
                for rank, (node_id, score, details) in enumerate(pagerank_nodes[:5], 1):
                    purpose = purpose_statements.get(node_id, "")
                    purpose_snippet = f" — {purpose[:120]}..." if purpose else ""
                    f.write(f"{rank}. **`{node_id}`** (score: {score:.4f}){purpose_snippet}\n")
                    f.write(f"   - *Why:* {details}\n")
            else:
                f.write("*(PageRank unavailable — graph may be empty)*\n")
            f.write("\n")

            # ── Section 3: Data Sources & Sinks ───────────────────────
            f.write("## 3. Data Sources & Sinks\n\n")
            sources, sinks = self._get_sources_and_sinks(lineage_graph)

            f.write("### Sources (no upstream dependencies)\n\n")
            if sources:
                for s in sorted(sources)[:20]:
                    f.write(f"- `{s}`\n")
            else:
                f.write("*(none detected)*\n")
            f.write("\n")

            f.write("### Sinks (no downstream dependents)\n\n")
            if sinks:
                for s in sorted(sinks)[:20]:
                    f.write(f"- `{s}`\n")
            else:
                f.write("*(none detected)*\n")
            f.write("\n")

            # ── Section 4: Known Debt ──────────────────────────────────
            f.write("## 4. Known Debt\n\n")

            # 4a. Circular dependencies
            cycles = self._get_cycles(lineage_graph)
            f.write(f"### Circular Dependencies: {len(cycles)}\n\n")
            if cycles:
                for cycle in cycles[:5]:
                    f.write(f"- `{'` → `'.join(cycle)}`\n")
            else:
                f.write("✅ No circular dependencies detected.\n")
            f.write("\n")

            # 4b. Doc drift
            drift_items = {k: v for k, v in drift_flags.items() if not _is_pseudo(k)}
            f.write(f"### Documentation Drift: {len(drift_items)} flag(s)\n\n")
            if drift_items:
                for mod_id, flag in sorted(drift_items.items()):
                    verdict = flag.get("verdict", "UNKNOWN")
                    explanation = flag.get("explanation", "")
                    icon = "⚠️" if verdict == "DRIFT" else "❌"
                    f.write(f"- {icon} **{verdict}** `{mod_id}` — {explanation}\n")
            else:
                f.write("✅ No documentation drift detected.\n")
            f.write("\n")

            # 4c. Orphaned nodes
            orphaned = self._get_orphans(lineage_graph)
            f.write(f"### Orphaned Nodes: {len(orphaned)}\n\n")
            if orphaned:
                for node_id in sorted(orphaned):
                    f.write(f"- `{node_id}`\n")
            else:
                f.write("✅ No orphaned nodes detected.\n")
            f.write("\n")

            # 4d. Semantic Anomalies
            anomalies = self._get_semantic_anomalies(lineage_graph, purpose_statements)
            f.write(f"### Semantic Anomalies: {len(anomalies)}\n\n")
            if anomalies:
                for target, issue in anomalies:
                    f.write(f"- 🚩 **CONFLICT** `{target}`: {issue}\n")
            else:
                f.write("✅ No structural-to-semantic contradictions detected.\n")
            f.write("\n")

            # ── Section 5: High-Velocity Files ────────────────────────
            f.write("## 5. High-Velocity Files\n\n")
            f.write("*Files with the most commits in the last 30 days — likely pain points.*\n\n")
            if git_velocity:
                top = sorted(git_velocity.items(), key=lambda x: x[1], reverse=True)[:15]
                for file_path, commits in top:
                    bar = "█" * min(commits, 20)
                    f.write(f"- `{file_path}` — **{commits}** commits {bar}\n")
            else:
                f.write("*(git velocity data not available)*\n")
            f.write("\n")

            # ── Section 6: Domain Module Index ────────────────────────
            f.write("## 6. Module Purpose Index\n\n")
            f.write(
                "*Grouped by inferred business domain. Purpose statements grounded in code, not docstrings.*\n\n"
            )

            # Normalise all node IDs to backslash to prevent slash/backslash
            # duplicates (e.g. "load/loaders.py" vs "load\loaders.py")
            def _norm(p: str) -> str:
                return p.replace("/", "\\")

            # Group modules by domain, filter pseudo-nodes
            domains: dict[str, list[str]] = {}
            seen_in_domain: set = set()
            for mod_id, domain in domain_map.items():
                if _is_pseudo(mod_id):
                    continue
                n = _norm(mod_id)
                if n not in seen_in_domain:
                    seen_in_domain.add(n)
                    domains.setdefault(domain, []).append(n)

            # Include modules not in domain_map — deduplicated
            mapped_norm = {_norm(k) for k in domain_map.keys()}
            seen_all: set = set()
            unclustered = []
            for node in module_graph.graph.nodes:
                if _is_pseudo(node):
                    continue
                n = _norm(node)
                if n not in seen_all:
                    seen_all.add(n)
                    if n not in mapped_norm:
                        unclustered.append(n)
            if unclustered:
                domains.setdefault("unclustered", unclustered)

            for domain in sorted(domains.keys()):
                f.write(f"### Domain: **{domain.replace('_', ' ').title()}**\n\n")
                for mod_id in sorted(set(domains[domain])):
                    # Look up node data trying both slash variants
                    mod_data = (
                        module_graph.graph.nodes.get(mod_id)
                        or module_graph.graph.nodes.get(mod_id.replace("\\", "/"))
                        or {}
                    )
                    file_type = mod_data.get("file_type", "unknown")
                    # Look up purpose trying both variants
                    purpose = (
                        purpose_statements.get(mod_id)
                        or purpose_statements.get(mod_id.replace("\\", "/"))
                        or "*(no purpose extracted)*"
                    )

                    f.write(f"#### `{mod_id}` [{file_type}]\n\n")
                    f.write(f"**Purpose:** {purpose}\n\n")

                    # Drift warning — try both slash variants
                    drift_data = drift_flags.get(mod_id) or drift_flags.get(
                        mod_id.replace("\\", "/")
                    )
                    if drift_data and not _is_pseudo(mod_id):
                        flag = drift_data
                        verdict = flag.get("verdict", "UNKNOWN")
                        expl = flag.get("explanation", "")
                        f.write(f"> [!WARNING]\n> **Docstring {verdict}:** {expl}\n\n")

                    # Dependencies — try both slash variants, filter pseudo-nodes
                    g = lineage_graph.graph
                    alt = mod_id.replace("\\", "/")
                    node_in_graph = mod_id if mod_id in g else (alt if alt in g else None)
                    if node_in_graph:
                        upstream = [u for u, _ in g.in_edges(node_in_graph) if not _is_pseudo(u)]
                        downstream = [v for _, v in g.out_edges(node_in_graph) if not _is_pseudo(v)]
                        if upstream:
                            f.write(
                                "**Upstream:** "
                                + ", ".join(f"`{u}`" for u in sorted(upstream))
                                + "\n\n"
                            )
                        if downstream:
                            f.write(
                                "**Downstream:** "
                                + ", ".join(f"`{v}`" for v in sorted(downstream))
                                + "\n\n"
                            )

                f.write("---\n\n")

        logger.info("Generated CODEBASE.md → %s", path)

    # ------------------------------------------------------------------
    def _generate_audit_trace(
        self,
        module_graph: KnowledgeGraph,
        lineage_graph: KnowledgeGraph,
        semantic_results: dict,
    ) -> None:
        log_path = os.path.join(self.output_dir, "audit_trace.log")

        with open(log_path, "w", encoding="utf-8") as f:
            f.write(f"CARTOGRAPHER AUDIT TRACE — {datetime.now().isoformat()}\n")
            f.write(f"Target: {self.target_dir}\n")
            f.write(f"Modules Scanned:            {len(module_graph.graph.nodes)}\n")
            f.write(f"Lineage Nodes:              {len(lineage_graph.graph.nodes)}\n")
            f.write(f"Lineage Edges:              {len(lineage_graph.graph.edges)}\n")

            failed = [
                nid
                for nid, attrs in lineage_graph.graph.nodes(data=True)
                if attrs.get("parsed") is False
            ]
            f.write(f"Parse Failures:             {len(failed)}\n")

            purposes = semantic_results.get("purpose_statements", {})
            f.write(f"Purpose Statements:         {len(purposes)}\n")

            drift = {
                k: v
                for k, v in semantic_results.get("drift_flags", {}).items()
                if not _is_pseudo(k)
            }
            f.write(f"Doc Drift Flags:            {len(drift)}\n")
            for mod_id, data in sorted(drift.items()):
                f.write(f"  [{data.get('verdict')}] {mod_id}\n")

            budget = semantic_results.get("budget_summary", {})
            if budget:
                f.write("\nLLM Budget:\n")
                for model, calls in budget.get("calls_per_model", {}).items():
                    tokens = budget.get("estimated_tokens_per_model", {}).get(model, 0)
                    f.write(f"  {model}: {calls} calls, ~{tokens} tokens\n")

        logger.info("Generated audit_trace.log → %s", log_path)

    # ------------------------------------------------------------------
    # Graph helpers
    # ------------------------------------------------------------------

    def _get_pagerank(self, graph: KnowledgeGraph):
        """Returns [(node_id, score, derivation_text)] sorted descending."""
        try:
            import networkx as nx

            pr = nx.pagerank(graph.graph, alpha=0.85)
            filtered = {k: v for k, v in pr.items() if not _is_pseudo(k) and not _is_macro(k)}
            sorted_nodes = sorted(filtered.items(), key=lambda x: x[1], reverse=True)

            results = []
            for nid, score in sorted_nodes:
                in_deg = graph.graph.in_degree(nid)
                out_deg = graph.graph.out_degree(nid)
                derivation = f"Centrality driven by {in_deg} upstream sources and {out_deg} downstream dependents."
                results.append((nid, score, derivation))
            return results
        except Exception:
            return []

    def _get_sources_and_sinks(self, graph: KnowledgeGraph):
        """Nodes with in-degree=0 (sources) and out-degree=0 (sinks), pseudo-nodes and macros excluded."""
        sources, sinks = [], []
        for node in graph.graph.nodes:
            if _is_pseudo(node) or _is_macro(node):
                continue
            if graph.graph.in_degree(node) == 0:
                sources.append(node)
            if graph.graph.out_degree(node) == 0:
                sinks.append(node)
        return sources, sinks

    def _get_cycles(self, graph: KnowledgeGraph) -> list[list[str]]:
        """Returns list of cycles (each a list of node ids)."""
        try:
            import networkx as nx

            return list(nx.simple_cycles(graph.graph))
        except Exception:
            return []

    def _get_orphans(self, graph: KnowledgeGraph) -> list[str]:
        """Nodes with no edges at all, pseudo-nodes and macros excluded."""
        nodes_with_edges = {n for u, v in graph.graph.edges() for n in (u, v)}
        return [
            n
            for n in graph.graph.nodes
            if n not in nodes_with_edges and not _is_pseudo(n) and not _is_macro(n)
        ]

    def _get_semantic_anomalies(
        self, graph: KnowledgeGraph, purpose_statements: dict
    ) -> list[tuple[str, str]]:
        """Detects contradictions between graph structure and LLM purpose strings."""
        anomalies = []
        for node_id, purpose in purpose_statements.items():
            if _is_pseudo(node_id):
                continue

            p_lower = purpose.lower()
            in_deg = graph.graph.in_degree(node_id)
            out_deg = graph.graph.out_degree(node_id)

            # Contradiction: Purpose says it's a "source" or "ingestion" but it has upstreams
            if ("source" in p_lower or "ingest" in p_lower) and in_deg > 0:
                anomalies.append(
                    (
                        node_id,
                        f"Purpose claims it's a source, but graph shows {in_deg} upstream dependencies.",
                    )
                )

            # Contradiction: Purpose says it's an "output" or "final" but it has downstreams
            if ("output" in p_lower or "final" in p_lower) and out_deg > 0:
                anomalies.append(
                    (
                        node_id,
                        f"Purpose claims it's a final output, but graph shows {out_deg} downstream dependents.",
                    )
                )

        return anomalies
