import os
import json
from datetime import datetime
from ..graph.knowledge_graph import KnowledgeGraph


class Archivist:
    """
    Phase 4 — The Archivist Agent
    Packages the extracted knowledge and LLM-generated insights into
    human-readable, persistent documentation.
    """

    def __init__(self, target_dir: str):
        self.target_dir = target_dir
        self.output_dir = os.path.join(os.getcwd(), ".cartography")
        os.makedirs(self.output_dir, exist_ok=True)

    def archive(
        self,
        module_graph: KnowledgeGraph,
        lineage_graph: KnowledgeGraph,
        semantic_results: dict,
    ) -> None:
        """
        Produce:
        - CODEBASE.md: A structured, readable report of domains and modules.
        - onboarding_brief.md: (Already written by Semanticist, but Archivist can append/enhance)
        - audit_trace.log: Summary of what was found and logged.
        """
        print("\n[Archivist] ===== Phase 4 Starting =====")

        self._generate_codebase_md(module_graph, lineage_graph, semantic_results)
        self._generate_audit_trace(module_graph, lineage_graph, semantic_results)

        print("[Archivist] ===== Phase 4 Complete =====\n")

    def _generate_codebase_md(
        self,
        module_graph: KnowledgeGraph,
        lineage_graph: KnowledgeGraph,
        semantic_results: dict,
    ) -> None:
        """Generates the primary documentation artifact."""
        codebase_path = os.path.join(self.output_dir, "CODEBASE.md")

        purpose_statements = semantic_results.get("purpose_statements", {})
        domain_map = semantic_results.get("domain_map", {})
        drift_flags = semantic_results.get("drift_flags", {})

        # Group modules by domain
        domains = {}
        for mod_id, domain in domain_map.items():
            if domain not in domains:
                domains[domain] = []
            domains[domain].append(mod_id)

        with open(codebase_path, "w", encoding="utf-8") as f:
            f.write("# Project Codebase Architecture\n\n")
            f.write(f"*Auto-generated by Brownfield Cartographer on {datetime.now().strftime('%Y-%m-%d')}*\n\n")

            f.write("## Overview\n\n")
            f.write(f"This document details the modular structure of `{self.target_dir}`.\n")
            f.write(f"Identified {len(domains)} distinct business domains from the source code.\n\n")

            f.write("## Domain Modules\n\n")

            # Sort domains alphabetically
            for domain in sorted(domains.keys()):
                f.write(f"### Domain: {domain.title()}\n\n")

                # Sort modules within domain
                modules = sorted(domains[domain])
                for mod_id in modules:
                    # Basic attributes from graph
                    mod_data = module_graph.graph.nodes.get(mod_id, {})
                    file_type = mod_data.get("file_type", "unknown")
                    
                    purpose = purpose_statements.get(mod_id, "*(No semantic purpose extracted)*")

                    f.write(f"#### `{mod_id}` [{file_type}]\n\n")
                    f.write(f"**Purpose:** {purpose}\n\n")

                    # Drift warning
                    if mod_id in drift_flags:
                        flag_data = drift_flags[mod_id]
                        verdict = flag_data.get("verdict", "UNKNOWN")
                        explanation = flag_data.get("explanation", "")
                        f.write(f"> [!WARNING]\n> **Docstring {verdict}:** {explanation}\n\n")

                    # Dependencies (Upstream / Downstream) based on Lineage Graph
                    upstream = []
                    downstream = []
                    
                    if mod_id in lineage_graph.graph:
                        # Find incoming edges (upstream)
                        for u, _ in lineage_graph.graph.in_edges(mod_id):
                            upstream.append(u)
                        # Find outgoing edges (downstream)
                        for _, v in lineage_graph.graph.out_edges(mod_id):
                            downstream.append(v)
                            
                    if upstream:
                        f.write("**Upstream Dependencies:**\n")
                        for u in sorted(upstream):
                            f.write(f"- `{u}`\n")
                        f.write("\n")
                        
                    if downstream:
                        f.write("**Downstream Dependents:**\n")
                        for v in sorted(downstream):
                            f.write(f"- `{v}`\n")
                        f.write("\n")

                f.write("---\n\n")

        print(f"[Archivist] Generated CODEBASE.md → {codebase_path}")

    def _generate_audit_trace(
        self,
        module_graph: KnowledgeGraph,
        lineage_graph: KnowledgeGraph,
        semantic_results: dict,
    ) -> None:
        """Generates a simple execution trace log."""
        log_path = os.path.join(self.output_dir, "audit_trace.log")

        with open(log_path, "w", encoding="utf-8") as f:
            f.write(f"CARTOGRAPHER AUDIT TRACE - {datetime.now().isoformat()}\n")
            f.write(f"Target: {self.target_dir}\n")
            f.write(f"Total Modules Scanned: {len(module_graph.graph.nodes)}\n")
            f.write(f"Total Lineage Edges: {len(lineage_graph.graph.edges)}\n")

            failed_nodes = [
                nid for nid, attrs in lineage_graph.graph.nodes(data=True) if attrs.get("parsed") is False
            ]
            f.write(f"Parse Failures: {len(failed_nodes)}\n")
            
            purpose_stmts = semantic_results.get("purpose_statements", {})
            f.write(f"Purpose Statements Generated: {len(purpose_stmts)}\n")

            drift = semantic_results.get("drift_flags", {})
            f.write(f"Doc Drift Flags Raised: {len(drift)}\n")
            for mod_id, data in drift.items():
                f.write(f"  - [{data.get('verdict')}] {mod_id}\n")

        print(f"[Archivist] Generated audit trace → {log_path}")
